version: '3.8'

services:
  app:
    image: laravel-app:latest
    container_name: tasktracker-app
    ports:
      - "8000:8000"
    volumes:
      - appdata:/var/www/html/database
    restart: unless-stopped

volumes:
  appdata: